# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6a6005b7e97c06d23e293a82042d3df1f8f3cb6a209b768be8e60dd28948886b3ad5c7a716d9c364b78d33ce54a7899edc7a11e09c7b3e01484f41f80540ffd

test:
  secret_key_base: 1ce40d3344523dc4913717fc331bb20d830eff199a0f96e4cafa32e9b85aae436d66089a920acc90ecc90ed84043c9f16b73bf1b56e076eb6c3fadcd86651170

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
